hydra.c
With inputs like ./hydra -l admin -P passwords/dictionary.txt
hydra gives a segmentation fault. Now checks if index < argc after
trying to access to argv[index]
=> Fixed segfault checking command line arguments

hydra-oracle-listener.c, hydra-smb.c, hydra-snmp.c
uses deprecated des_ methods and types that were marked deprecated by
OpenSSL 0.9.7 and will be removed in OpenSSL 1.1.0 . This patch replaces
the des_ methods and types with their new DES_ counterparts. This
enables building with LibreSSL as OpenSSL library.
Check https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/des/des_old.h for the compatibility macros that have been removed.
=> Replace deprecated des_ and fix LibreSSL build

Makefile.am
this patch introduces DATADIR, MANDIR and DESTDIR to it is possible
to configure the csv data location, the man location and also a
packaging DESTDIR location which is needed for packaging in a subdir.
PREFIX stays like it was so it is properly used in dpl4hydra.sh.
The old locations and behavior should still be the same if you don't override any of the new variables, so this patch should not change any of the "old" default locations but adds the possibility to distribute to any arbitrary location (dpl4hydra.sh respects those by introducing another sed command for LOCATION).
Just as an example, I use this patch to package hydra for ArchLinux via:
./configure --prefix=/usr
make
make DESTDIR="${pkgdir}" MANDIR="/share/man/man1" DATADIR="/share/${pkgname}" install
=> adding make location configurations to ease proper packaging

hydra-mod.c
Uses `TLSv1_client_method` if `TLSv1_2_client_method` is not defined as a symbol in OpenSSL.
=> Allow compilation with older openssl

Android.mk
from android 6.0 google throw away the openssl library to use a lighter ssl library.
with this change openssl will be compiled statically into hydra, making it independent from underlay ssl implementation.
=> Fix missing openssl library on android 6.0

Android.mk, hydra-rdp.c
sorry for coming out later with these commits, I installed an android 6.0 emulator and tested out the whole stuff.
it should be `libssl_static`, not `libssl`, and it must be before `libcrypto_static`.
hydra define the function `ssl_cert_free`, that is also defined in openssl library.
solution to this problem is to define that function as file-scoped ( static ).
this will also fix hydra for anyone that want to build it statically with openssl library built-in.
thank you for your patience @vanhauser-thc :blush:
=> use static version of the ssl library

configure
As mentioned by users in #80, since adding the prefix the compilation is broken unless the SSL prefix is used.
=> Fix issue with hydra not compiling since adding custom ssl prefix

configure
If they are compiling to target an alternative directory there are likely dependencies to the same target.  Test for PREFIX/lib and PREFIX/include to be sure.
=> If prefix set then high chance of libs being there

hydra-ssh.c
The problem was detected while trying to brute ssh server. 
Once hydra reached limit in 6 attempts (default MaxAuthTries value for sshd), server disconnected it, but hydra didn't reconnect to ssh and kept trying next passwords in closed session. When i checked sshd logs, i saw that there wasn't any login attempts after first disconnect.
This bug caused the problem: hydra hadn't crack ssh, even if correct password was in dictionary. 
As said on [libssh docs](http://api.libssh.org/stable/group__libssh__auth.html), userauth functions return SSH_AUTH_ERROR only in case of serious problems, it means that disconnect is standard situation and should be checked using ssh_is_connected(session) function.
=> ssh disconnect miss bug fixed

hydra-redis.c
This is a fix for the cases of old redis versions.
=> service_redis_init support of old redis < 3.0 (issue  #105)

hydra-imap.c, hydra-nntp.c, hydra-pop3.c, hydra-smtp.c
By standard C 11 if sprintf has same source and destination it is UB. Fixed by adding intermediate buffer
=> Fix several undefined behaviors

hydra-http-form.c
Off by one error found when processing Location: in redirects. on lines 792-793
Pointer handling mistake found when updating cookies after redirect.
When the process_cookies function gets called it expects a pointer to a pointer to a cookie_node, instead it gets a pointer to a cookie_node, derefs the cookie_node struct and lands in the middle of invalid memory.
=> Fix for #116

hydra-gtk/src/callbacks.c, hydra-gtk/src/interface.c
The patch fixes wrong behavior in xHydra, for SNMP for versions 1 and 2.
It also adds version 3 and options as MD5, SHA, AES, READ, …
=> Patch for xHydra SNMP

configure, hydra-http-form.c
changes summary
```
remove GCCSEC options to compile on sunos
add -lrt to support nanosleep()
add definition of strndup()
```
=> SunOS compile support

hydra.1
A missing newline lead to https://bugs.debian.org/853807
=> Fix manpage adding a missing newline

README, hydra-mod.c, hydra.c
* One bug (doh!  JSON comma in wrong spot)
* Mixed up the JSON "success message" response per comments from a few people (we're still beta, so it's okay to break things right now).
* Added a section to the README about -b and JSON
* Apple now calls it MacOS instead of OSX.  Just being persnickety here.
=> Updates to JSON code

hydra.c
sizeof(int) is not necessarily the same as the pointer size. On my amd64
system sizeof(int) is 4 bytes while the pointer size is 8 bytes. The
change solves https://github.com/vanhauser-thc/thc-hydra/issues/27 for
me.
=> do not assume sizeof(int) is the pointer size

hydra-http-form.c
fix following 2 issues:
1. when fail is a redirect url, matched is not - but the redirect flag is still 1 - causing match missed
2. when redirect to a relative url on a port not 80, it fails to attach the port to the redirect url
=> Reset redirect flag and fix redirect port error issue

hydra-gtk/src/interface.c, hydra.1, xhydra.1
The two commits add radmin2 to both the xhydra selection and the hydra man page.  I've also dropped the listing of modules from the xhydra man page to reduce the duplication and made a few minor markup changes.
Thanks for always being open to minor changes (and improving the spelling even more after the last PR)!
=> add radmin2 to xhydra selection and man page

configure
Should fix https://github.com/vanhauser-thc/thc-hydra/issues/255.
=> configure: find math.h on Xcode-only macOS systems

hydra-http-form.c
Fixes issue [#267](https://github.com/vanhauser-thc/thc-hydra/issues/267): http-get-form does not send absolute URL with an http proxy
=> Fixes issue #267

hydra.c
This PR removes an extra `/` which appears in the current hydra's output like this:
```
[DATA] attacking http-get://foo.com:80//bar/
```
And change it to be like this:
```
[DATA] attacking http-get://foo.com:80/bar/
```
The `hydra_options.miscptr` parameter will be checked if it starts with a slash then no need to add another one. If you would like to fix the issue in another way please let me know so I can fix it in an appropriate way.
The command used during testing:
```
hydra -l user -P mylist http-get://foo.com/bar/
```
=> Don't add extra slash to url if exist

hydra-http-form.c, hydra-http.c, hydra-http.h
This adds support for optionally adding headers to `http-get` and `http-post` via `(h|H)=My-Hdr\: foo`. I believe this should close #321 and #100. Please let me know if I've made any mistakes or if there's anything you'd like to see changed. Thanks!
=> Optionally add request headers to http-get

hydra-mongodb.c
Tiny change, there's a duplicated function name: dummy_mcached.
=> Fix compilation error when Mongo and Memcache libraries are absent

hydra.c
Hi,
My last PR did ignore the -R situation. This time I fixed this problem.
Now the JSON output file will be rebuilt when the session is first started, and in the -R it append.
I have tested that the JSON output is correct whether it's new or restored.
PS:
I try to make this clean, so I add a new "outfile_open_type" to avoid repeated "fopen".
Thanks & Regards,
Galaxy
=> Rebuild JSON report file in first time and append while using -R

hydra-http-form.c
There was a mistake in pointer offset value in advanced options of HTTP/HTTPS modules.
Also, the description of the option and the format of the output information were fixed.
=> Header value parsing fix and some misc changes

configure, hydra-svn.c
On Gentoo Linux (and possibly others?) with Subversion 1.12.0,
compilation of hydra-svn.c fails with:
In file included from /usr/include/subversion-1/svn_client.h:34,
from hydra-svn.c:9:
/usr/include/apr-1/apr.h:632:2: error: #error no decision has been made on APR_PATH_MAX for your platform
#error no decision has been made on APR_PATH_MAX for your platform
^~~~~
This happens when PATH_MAX is not defined.
PATH_MAX is defined by /usr/include/linux/limits.h, but rather than
include'ing that directly and possibly breaking other platforms,
include sys/param.h (which will include linux/limits.h indirectly)
iff PATH_MAX is not defined and sys/param.h exists.
I based the approach on how math.h is handled.
=> Worked around APR_PATH_MAX errors on some Linuxes when SVN is enabled.

hydra.c
Hi, I know that it's looks like a crunch, but when user send `-C /tmp` hydra start endless loop in hydra.c:L1054-L1090. Add flag which trigered if nothing readed.
And good case 
Close https://github.com/vanhauser-thc/thc-hydra/issues/316
=> Fix dump with folder

hydra-gtk/src/callbacks.c, hydra-gtk/src/interface.c
Patch for xhydra (as suggested in #487) to support smb2 module.
=> Updated xhydra to support smb2

hydra-vnc.c
A compiler warning told me that buf was used uninitialised here and it
turned out that instead of buf2, buf was being used. It makes a lot more
sense to report buf2 and that happens to fix the warning as well.
=> hydra-vnc: Use buf2 instead of buf in hydra_report

configure
For example on the Fedora 31 the path for the firebird include ibase.h is /usr/include/firebird/ibase.
This patch should also consider the firebird subdirectory inside the regular include directory.
=> Consider the /usr/include/firebird/ path for fb

hydra-http-form.c
The pre-request is used to get cookies. But sometimes it is unnecessary and it reduce the performence.
=> Add optional option to skip pre-request

hydra-http-proxy.c
I was just trying to use `http-proxy` module, but found it was not working as it was assuming the result of `hydra_receive_line` was a single line of text, whereas it actually returns the contents of the receive buffer with null bytes replaced by spaces. Maybe there was some refactoring of the code in the past and `http-proxy` was not updated? I should note as well that I have only tested the basic auth pathways of the code.
Also, added a patch to clean the compile from `sprintf` warnings (at least for `gcc version 9.3.0`).
Finally, added a patch to add http 404 response as a success condition as this is typically from the target server and not the proxy, so its reasonable to assume the authentication was ok in this case. If this is not correct, I can drop this one :)
=> http-proxy: Fix for multiline buffer

Makefile.am, configure, hydra-rdp.c, hydra.c
The newest version of freerdp is v.3, updating Hydra to support this new module. 
Have tested this on my Ubuntu 18.04 LTS using latest build from freerdp and thc-hydra at time of writing.
=> Updating hydra support for freedrdp 3

hydra-http-form.c
Hello.
I tried your awesome tool using emails as `^USER^` in a http `GET` request.
In my wordlist some email addresses contain "+" (for alias).
It seems thc-hydra doesn't url-encode the "+" failing the request, so I added it to the url-encodable character in this PR.
What do you think ? 😄 
Thank you in advance.
=> html_encode the + character

hydra-http-form.c, hydra.c
Hello,
I noticed that when using the http-form module with an ipv6 address that it was failing to work. After investigation, it appears the `Host` header was not correctly formatted, resulting in the following:
Essentially, it should include the square brackets around the address. I noticed another issue on another project that had the same problem and provides links to the RFC's https://github.com/dotnet/runtime/issues/25661#issuecomment-377023158
While tweaking the `Host` header, I noticed the following *if* statement which complicated the code and as far as I can tell guarded dead code (as it expects the `miscptr` to contain `://`) and the only effect of the statement was to set `webtarget = null` due to `strstr`.
https://github.com/vanhauser-thc/thc-hydra/blob/c2260d2c5d55a40e5ed51d9f9 …
=> http-form: ipv6 fix 

hydra.c
username can potentially be identical to the beginning of login_ptr
=> fix: skip user bug

hydra-mongodb.c
mongodb module does not use specified due to omission of the port argument in the string formatter.
=> fix mongodb module not using specified port

hydra-gtk/configure.in
gtk3 is more modern and successor to the old gtk2
=> hydra-gtk: update to gtk3

configure
On Debian/Ubuntu, compilation against openssl 3.0 causes a failure to
find INT_MAX, despite the openssl headers including limits.h.  However,
the fact that the libmemcached-dev package provides both
/usr/include/libmemcached{,-1.0} directories, both of which contain
memcached.h, mean that MCACHED_IPATH ends up set to the libmemcached-1.0
one, which contains a limits.h, which shadows /usr/include/limits.h.
Don't do that.
Not sure how this plays out in other build environments, so feel free to
decline or suggest changes.  Thanks!
=> configure: openssl / memcached build fix

hydra-gtk/src/main.c
This small change makes Xhydra work smoothly in termux x11
=> hydra-gtk: add support for termux path

hydra-radmin2.c
`msg` is calloc'd a few lines above via `msg = buffer2message(buffer);`.
The check afterwards either exits the process on success or restarts the
loop without free'ing `msg`.
=> Fix memory leak in radmin2

Makefile.am
strcasestr is not a standard function and per
the man page, needs -D_GNU_SOURCE to be visible.
Fixes a build error:
```
hydra-rtsp.c:20:7: error: implicit declaration of function ‘strcasestr’; did you mean ‘strcasecmp’? [-Werror=implicit-function-declaration]
20 |   if (strcasestr(s, "401 Unauthorized") != NULL) {
|       ^~~~~~~~~~
|       strcasecmp
```
Signed-off-by: Sam James <sam@gentoo.org>
=> Makefile.am: add -D_GNU_SOURCE for strcasestr

hydra-rdp.c
fix:
freerdp default set tls-seclevel level to 1, connection failed to establish
https://github.com/vanhauser-thc/thc-hydra/issues/806
=> freerdp tls-seclevel to 0

configure, hydra-gtk/configure, hydra-rtsp.c
strrchr is declared in <strings.h>, not <string.h>.
_GNU_SOURCE needs to be defined before any glibc headers are included, otherwise it is not effective.
Also patch some old autoconf-internal issues in the hydra-gtk configure script.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
=> Various C99 compatibility fixes

hydra-mongodb.c
Hydra gets stuck When brute force mongodb with empty username and empty password.
- Hydra version: build from master branch
```
$ hydra -l "" -p "" -I  -v mongodb://127.0.0.1
Hydra v9.5-dev (c) 2023 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).
Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2023-02-10 07:29:24
[INFO] The mongodb db wasn't passed so using admin by default
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking mongodb://127.0.0.1:27017/
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[INFO] Using default database "admin"
```
Then it stucked...
The simple way …
=> fix: program stuck when mongodb user is empty

hydra-mongodb.c
I found this error while using hydra for multi-password testing against mongodb.
In the original code, if the tested username and password pair is wrong, **hydra_completed_pair_skip()** will be called, and this time a flag will be set to "f", that is, username identified as invalid. Then, **hydra_skip_user()** is called afterwards, which causes the username to be skipped for this test. If there are other correct passwords in the password list, they will not be tested.
So the **hydra_completed_pair_skip()** function should be changed to **hydra_completed_pair()** so that the user name is not skipped.
Also, if the password test fails, returning 2 will exit the child thread, which is wrong. **Should return 1**, continue with the next test.
=> edit mongodb moudle error

hydra.c
when proxy_count=64, array proxy_string_port , proxy_string_ip, etc. may out of bound.
=> fix: array proxy_string_port may out of bound

hydra-rtsp.c
There was a `_GNU_SOURCE` redefined warning that is no longer there.
Cheers.
=> Fixed #868 on vanhauser-thc/thc-hydra

hydra.c
I had a site which returns 200OK, but a json containing 403. Get results in "invalid api call". Allow using F= with post.
=> Allow HTTP-POST with F=403

hydra-ssh.c
Legacy SSH ciphers (for Key Exchange and Host Keys) was missing from the default cipher list, it is needed to specify it in custom libssh options. Here are some common useful extra legacy ciphers added.
NOTE: Currently this hardcoded list is working, but for the future it might be better to _add_ the legacy ciphers to the default ones, not defining the full list (if some new ciphers will be added to the defaults automatically in libssh).
=> add legacy SSH ciphers support

hydra-rdp.c
FreeRDP/FreeRDP#7738
use settings field under `instance->context` instead of `instance`.
FreeRDP/FreeRDP@5f81005ecbd87d043f2ce39ea11c98065b1a1923
removes reference to MaxTimeInCheckLoop for version 3 since FreeRDP has dropped this field after migrating away from blocking poll loop.
=> Fix compile errors when compiling against freerdp3

Dockerfile
Since Debian Buster's LTS support ends next month, I suggest updating the base image in the Dockerfile to Debian Bookworm.
=> Bump Debian version in Dockerfile to Bookworm 

hydra-smb.c
- If SMB password is MUST_CHANGE or EXPIRED, it is still valid, it is possible to change it remotely, so it should be returned as valid.
- If the _account_ is EXPIRED, it is no longer usable, even if the password is ok. It should be returned as invalid.
Testing is in this thread: https://twitter.com/an0n_r0/status/1731109539204710416
Originally Hydra returned valid if the account was expired but invalid if the password was expired. It is wrong, it should be exactly the opposite: valid if password was expired, but invalid if account was expired.
=> fix smb password expired vs account expired confusion

hydra.c, hydra.h
resolves #386 
Added command line option to divide up wordlists on the fly. multiple processes or servers could be launched at once to  each use different parts of the wordlist, but there is no synchronisation or reporting of success as of yet, so this would have to be done manually.
=> Add distributed computing

hydra-pop3.c
Some POP3 servers contain many capabilities, so `+OK` and `\r\n.\r\n` Contained in different blocks, and the tool is looped. This code corrects this behavior
=> POP3 CAPA response fix

hydra-http-form.c
Fix wrong spell from "seperate" to "separate".
Debian lintian show this warning :)
=> Fix spelling
