vanhauser-thc/thc-hydra

Makefile.am
hydra-rtsp.c
hydra.c
hydra.h
sasl.c

Hi, i send you a mail yesterday. I'll wait you answer.
Thanks van Hauser.

hydra-rtsp.c

---

hydra-gtk/src/callbacks.c
hydra-gtk/src/interface.c

The patch adds the -O option to xHydra

-O option to xHydra

---

bfg.c
bfg.h
hydra.c

Fixed adding a new option (-y) that disable brute force placeholders.
Small fix added, as well.
This closes #148 .

Fix issue #148.

---

hydra-mod.c
hydra-rdp.c

- Tested with LibreSSL 2.5.0 on OpenBSD current amd64

add LibreSSL support

---

hydra-redis.c

The patch fixes a bug in the cases when the number of the tasks is smaller than the number of the passwords. Also includes improvement to support the features of the protocol.

Bug fix and module improvement

---

hydra-telnet.c

Fix false success for case like
`% Bad password`
`Invalid login/password`

Fix telnet complete condition

---

hydra.c

We have a need to parse the output of Hydra to flag issues for clients.  I have a script that does various cut/sed/perl to extract each bad user account, but a system that allows user IDs with spaces in names just made this more difficult.  So, I found it easier to modify Hydra to simply output this information in JSON.  This also simplifies our downstream processing of the data.  So, I am contributing this back to the community.
I added a new `-b` command line flag which requires a single parameter of `text`, `json`, or `jsonv1` to determine the format of results file.  Choosing `text`, the default, will output the results file exactly as it is now. However, `json` or `jsonv1`, will output the same information but in JSON format.  The options:
* `text` - output as it is now
* `json` - …

New feature: output results in JSON format.

---

CHANGES
hydra-gtk/make_xhydra.sh
hydra-gtk/src/interface.c
hydra-gtk/xhydra.glade
hydra-http-form.c
hydra-http.c
hydra-ldap.c
hydra-mod.c
hydra-pop3.c
hydra-smtp-enum.c
hydra-smtp.c
hydra-snmp.c
hydra.1
hydra.c
ntlm.c
web/CHANGES

taken from Debian; the changes were authored by:
* Julián Moreno Patiño <julian@debian.org>
* Daniel Echeverry <epsilon77@gmail.com>

fix various spelling and typography errors

---

README.md

Since the repo is hosted on github, that renders the README.md straightforward, the conversion looks a good idea to me.

Change REAME to README.md.

---

.travis.yml

If you merge this file, you need to activate travis builds as well.

Add travis-ci file.

---

hydra-cisco.c
hydra-mod.c
hydra-radmin2.c
hydra-vmauthd.c
hydra-vnc.c
hydra.c

A first run with clang's ccc-analyzer showed some issues.

ccc-analyzer code audit.

---

.travis.yml
hydra-mod.h
hydra-rdp.c
hydra-sip.c

Some changes needed to compile on OSX with and without libcrypt.

Compile on OSX

---

pw-inspector.c

0a50b41be99f1b2fe2b1c2235a3a0a18c2d92f36 only solves half of the problem.
```
cc -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro    -o pw-inspector  pw-inspector.c
pw-inspector.c: In function 'main':
pw-inspector.c:40:3: error: unknown type name 'int32_t'
int32_t i, j, k;
^~~~~~~
[...]
```

fix build with musl libc

---

hydra-http-form.c
hydra.c

possible base64 encoding of credentials

---

hydra.c

Removed duplicates and unused code

General Cleanup

---

hydra-http-form.c

From the tests I've conducted, this seems to fix issue #347.  Please let me know if I've made any mistakes or if there's anything you'd like to see changed. Thanks!

set cookie for http-form-post redirects

---

hydra-ssh.c

make thread-safe against old ssl versions

---

hydra-rpcap.c

Hi! 
Fix a spelling error.
Regards!

Fix spelling error

---

hydra-mod.c
hydra.c

There are some miscellaneous changes that make the code easier to read

Misc fixes

---

hydra-http.c
hydra-mod.c

There is an issue with NTLM authentication.
First of all, while using an HTTPS module, Hydra sometimes results in false negative or freezes when receiving data from a socket. So, an additional check is necessary in a while loop (hydra_receive_line function):
```
#ifdef LIBOPENSSL
|| use_ssl && SSL_pending(ssl)
#endif
```
Second, there should be keep-alive value of Connection HTTP header (or it may be omitted since this is default behavior in HTTP/1.1) when NTLM authentication is used.
In addition, hydra_receive_line function has been rewritten, so it doesn't have a duplicate code now. I have tested it only for HTTP/HTTPS Basic and NTLM authentication types, but not for the other modules.

fix NTLM authentication

---

hydra-http-form.c

There should be an offset in the pointer value for everything to work properly

fix typo and the offset value of miscptr

---

hydra-smb2.c

Minor PR that fixes/identifies a case where invalid credentials are not properly identified.

SMB2: improved compatibility when null sessions fail

---

configure

PR for https://github.com/vanhauser-thc/thc-hydra/issues/519

libfreerdp2 and libwinpr2 fix in configure

---

configure

For https://github.com/vanhauser-thc/thc-hydra/issues/520

oracle on cygwin support

---

hydra-oracle.c

Hello,
I was just using the oracle module and noticed it was not finding valid credentials. After investigation the module was missing an acceptance case for accounts with password that will expire soon.
Also, I noticed that some of the user/password's were not being sent to the server. This is because the child was being exited after reading the next user/password pair (without using them).
Both of these are fixed in this PR.
Hope its of use.

oracle: add success condition and fix skipped tries

---

hydra.c

Usage: Fix help for https-post-form and https-get-form

---

configure

cf. https://github.com/vanhauser-thc/thc-hydra/issues/552

MSYS2 support

---

hydra-smb2.c

Hello,
Minor PR that resolves an issue when parsing the `miscptr` a second time - I didnt realise this was possible.
It also adds couple extra print statements for warnings/errors :smiley:

smb2: fix parsing of miscptr

---

hydra-http.c

As requested in https://github.com/vanhauser-thc/thc-hydra/pull/579#issuecomment-735768540 this PR aligns the http-get module with the patch for http-form module in #579.

http-get: ipv6 fix

---

hydra-smb.c

I can provide another patch version, which swaps the operands instead.
Signed-off-by: Christian Inci <chris.gh@broke-the-inter.net>

Fix logic bug

---

hydra-http-form.c
hydra-http-proxy-urlenum.c
hydra-http-proxy.c
hydra-http.c
hydra-mod.c
hydra-telnet.c
hydra.c

Changed index() to strchr() because the index() function seems to be deprecated in some POSIX systems. Don't know if this affects any other part of the program.

Changed index() to strchr()

---

hydra-telnet.c

Some systems dont ask for the user, and instead give the user multiple attempts attempts at the password before switching back to asking for the username.
```
Trying 192.168.100.11...
Connected to 192.168.100.11.
Escape character is '^]'.
login: user
Password: *******
login incorrect.
Password: ********
login incorrect.
Password: *****
login incorrect.
login:
```
This PR changes the telnet protocol to detect the password prompt and get the next password to try.  Without this PR, hydra would get stuck in a timeout reading from the socket.

telnet detects password retries with same user

---

README

Checked the link, skipping the redirect HTTP => HTTPS this way 0:-)

README: HTTP => HTTPS

---

hydra-rdp.c

hydra waittime support freerdp: TcpConnectTimeout
https://github.com/vanhauser-thc/thc-hydra/issues/805
Options description of freerdp
https://github.com/FreeRDP/FreeRDP/blob/c5e425242a6b52cb4a70db09ba0afe9bd7b91087/libfreerdp/core/settings.c#L647

rdp: support hydra waittime

---

hydra-rdp.c

fix rdp response 0002000f not recognised as a failed attempt

---

hydra-http-form.c

fix memory leaks for cookie_header,you should free cookie_header before return

fix memory leaks for hydra-http-form.c

---

hydra-http-form.c

Proposed solution for https://github.com/vanhauser-thc/thc-hydra/issues/863

fix replacement of user/pass placeholders in http header
